### ISSUE TITLE
HREK: Foundation Decorator Browser Crashes When Opened

### ISSUE THREAD

**Issue by FaberTheCatgirl** [Joint-Issue-Tracker/Joint-Issue-Tracker#100]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

HREK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [X] Foundation (`Foundation.exe`)
- [ ] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

# Decorator Browser Crashes When Opened.

An object reference is not set to an instance of an object, possibly due to null code in Foundation, possibly originating in Bungie.Core.Datastore

![image](https://user-images.githubusercontent.com/103538724/231888301-cedf4cab-a92b-43c4-9a89-b38d646731e3.png)
![Screenshot 2023-04-13 143349](https://user-images.githubusercontent.com/103538724/231888336-00e83372-6e1e-411a-be4e-9d4275333137.png)
![image](https://user-images.githubusercontent.com/103538724/231888768-6c191a90-9cad-48dc-8b21-025c0ba7f6cf.png)
![image](https://user-images.githubusercontent.com/103538724/231888886-858ba01f-98bc-4a74-a069-869e262a3e34.png)
![image](https://user-images.githubusercontent.com/103538724/231889188-54e7826d-91a0-4b51-b663-3771c449148d.png)
![image](https://user-images.githubusercontent.com/103538724/231890547-f8487426-2675-4504-abf4-de8bb487d514.png)

### Reproduction steps

Open Foundation, Select Tools > Assets > Decorator Browser. Upon selecting Foundation will hard crash.

### Debug logs

[crash_handler_debug.txt](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/files/11226685/crash_handler_debug.txt)
[crash_info.txt](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/files/11226686/crash_info.txt)
[exception_info.txt](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/files/11226705/exception_info.txt)

### How often does the issue occur?

100%

### Issue impact

It would be nice to have a new way to manage my decorators as doing them using the old workflow of opening tags one at a time and not having an easy overview is very time-consuming

### Additional comments

The Tools Are Amazing :heart:

**Comment by Arttumiro** [comment]
Seems to work just fine for me, are you sure you have ran Tagwatcher?

https://imgur.com/k0MAzJZ

**Comment by FaberTheCatgirl** [comment]
I will run TagWatcher and confirm if the issue is persisting Tomorrow. Thanks for the response @Arttumiro 🙌

**Comment by FaberTheCatgirl** [comment]
So, it seems to work after running TagWatcher via `CMD` and directing it to my HREK Install directory, it was crashing upon running TagWatcher by itself so I had to manually direct it. It seems to be working as intended now.

Hopefully, in a future update, TagWatcher will direct itself by default to the editing kit it was installed with.

**Comment by FaberTheCatgirl** [comment]
First Command `TagWatcher` caused this crash
![image](https://user-images.githubusercontent.com/103538724/232343403-22da8829-3669-4082-b95f-72c77eac18d4.png)
Workaround is pointing it to the HREK Directory
![image](https://user-images.githubusercontent.com/103538724/232343290-ad876c0b-2d45-44da-9de4-bc7656c4287c.png)
After that Tagwatcher will initialize correctly
![image](https://user-images.githubusercontent.com/103538724/232343444-6f4efd1c-9f16-4b6d-8468-3cfc0c404f96.png)

**Comment by kornman00** [comment]
This should be resolved in the 2023/07/12 update.
