### ISSUE TITLE
H2EK: Modded strings won't read in MCC

### ISSUE THREAD

**Issue by xXFerginatorXx** [Joint-Issue-Tracker/Joint-Issue-Tracker#106]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

H2EK

### Which tools are affected by the issue?

- [X] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [X] Sapien (`sapien.exe`)
- [X] Standalone (`halox_tag_test.exe`)
- [X] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [X] In-game (MCC)

### Issue description

Trying to make goofy texts appear on hud when using certain weapons or vehicles or other interactable objects in Halo 2 but it appears it is officially broken. Krevil made a mod for this on https://github.com/Krevil/H2EKStringDump and I followed the instructions to a tee and still the modded text shows in Sapien/Standalone but not in MCC. Even if you replace the string_en.str it still will not work. Unclear if this occured after Halo 2 got a steam workshop or not. The modded strings still show if you check the .map file in assembly but just don't work in MCC. Unclear why this happens.

### Reproduction steps

1) I went to https://github.com/Krevil/H2EKStringDump
2) Downloaded files and placed them in H2EK\data (used english)
3) Went to H2EK\data\ui\hud to file hud_messages.txt
4) Made changes, in this case to the spectre turret when entering to test, and then save
5) Ran CMD as admin
6) Ran command G:\Program Files (x86)\Steam\steamapps\common\H2EK>tool new-strings "ui\hud" 
7) After success ran G:\Program Files (x86)\Steam\steamapps\common\H2EK>tool pack-unicode-strings en "G:\Program Files (x86)\Steam\steamapps\common\H2EK\data\strings_list.txt"
8) Check strings_en.str updated in H2EK\h2_fonts and test changes in sapien
9) Save Sapien scenario and convert to map file as well as put strings_en.str in Halo The Master Chief Collection\halo2\h2_fonts by replacing existing
10) Take .map file and place in containment.map for time being to test before steam workshop
11) See results didn't transfer

### How often does the issue occur?

100%

### Issue impact

This is happening to others that used the modded string tags that also reported it on the halo mod discord. 

Any wacky mods you make, like I did for Halo 2's old school donkey kong mod, will just display default text.

### Additional comments

I tried both .map in replacing the an existing map as well as steam workshop, no change. 

To get an example of what it looks like, here is a link to the discord post I made if what happens:

https://discord.com/channels/615301822474878977/1101048896127504395

Also the default vs the modded string edit

![2023-05-01_20_19_21-Halo__The_Master_Chief_Collection](https://user-images.githubusercontent.com/128125126/236663645-56f776ca-c44a-49d6-927b-d7711d676a92.png)

![2023-05-01_20_09_46-H2_Sapien_-_donkey_kong_extreme scenario](https://user-images.githubusercontent.com/128125126/236663648-725d45af-6afe-4e0c-b255-be8e74f291e3.png)

**Comment by kornman00** [comment]
This should be resolved in the 2023/07/12 update. You will need to rebuild your map using latest tools
