### ISSUE TITLE
H2AMPEK Consistant Crash when Swapping Equipment

### ISSUE THREAD

**Issue by Zidiath** [Joint-Issue-Tracker/Joint-Issue-Tracker#109]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

H2AEK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [X] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

Experiencing the following crash when attempting to swap any types of equipment inside of H2AMPEK Sapien. For my examples I am using the H4 Storm equipment however this also occurs on manually created brand new equipment tags.

stack:
version:
Groundhog sapien test x64 untracked Dec  6 2022 11:18:20
halt:
### ASSERTION FAILED:  at e:\jenkins\workspace\mcch2acode-release\mcc\release\h2a\shared\engine\source\blofeld\objects\objects.cpp,[#11018](https://support.halowaypoint.com/hc/requests/11018)
 got an object type we didn't expect (expected one of 0x00000004 but got [#3](https://support.halowaypoint.com/hc/requests/3)).
fatal error detected, current status was:
    session_id: Sun_05282023_205036@x64@Zidiath@ZIDIATH-BUILD04
    sound: init done
    map: loaded levels\sway\ca_zanzibar\ca_zanzibar
    game_instance: F434604A6D268FFA
    game_simulation: local
    game_playback: none
    designer_zone: switching to 0x0 ()
    cinematic_zone: switching to 0x0 ()
    bsp: initialization done 0x1 (ca_zanzibar_bsp01)
    zone_set: switched to [#0](https://support.halowaypoint.com/hc/requests/0) ('mp')
    minor_version: -1
    last_tag_sync: time 1
    game_tick: time 8157
    using 1GB mode: N/A
    system_milliseconds: time 335919
    timezone_seconds_offset_from_UTC: 18000

### Reproduction steps

Open any .scenario in H2AMPEK 
Spawn an H4 (just an example) Storm_jetpack 
Equip the Jetpack 
Spawn a H4 thruster_pack 
Swap your Jetpack for the Thruster_Pack 
Crash

### Debug logs

[crash_info.txt](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/files/11587408/crash_info.txt)
[debug_full(1).txt](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/files/11587410/debug_full.1.txt)

### How often does the issue occur?

100%

### Issue impact

Technically minimal, but it would be nice to be able to use the equipment in H2A, this has been the only roadblock with using said equipment.

### Additional comments

https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/assets/13132499/4096dcca-a654-409b-8f04-b1a643135a3b

**Comment by kornman00** [comment]
This should be resolved in the 2023/07/12 update.
