### ISSUE TITLE
MCC Feature Request - Custom Menu

### ISSUE THREAD

**Issue by Photolysis** [Joint-Issue-Tracker/Joint-Issue-Tracker#117]
### Issue type: Is this a bug or feature request?

Feature request

### Which game's editing kit is affected by the issue?

H1EK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [ ] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [X] In-game (MCC)

### Issue description

The MCC UI has the option to set variables used by the game engine, allowing the player to customise their experience. However, this is restricted to whatever options are provided by 343i.

A way of allowing players to define a custom XML-based menu to adjust parameters which are then passed over to the game engine on startup would be extremely helpful. Currently any form of customisation requires scripting to change globals within the engine itself, or using whatever options the native MCC menu presents.

This would be particularly helpful for custom campaign/firefight content.

For example, we'll imagine a map with the following globals and statup script which sets player equipment:

```
(global short player_pri_weap_id 0)

(script startup map_start
  (if (= player_pri_weap_id 0)
    (player_add_equipment (player0) start_ar false)
  ) 
  (if (= player_pri_weap_id 1)
    (player_add_equipment (player0) start_pistol false)
  )  
) 
```
  
  
The following proposed example allows the player to adjust two globals used to drive a map script which selects starting equipment (selected option must be different for primary and secondary weapons), and provides access to a child menu to adjust the gravity.

```
<mcc_menu>

<menu id=0 name="General Settings">

<item id=0 name="Primary Weapon" exclusive_with_item_id=1>
<item_description>Adjust the player's starting primary weapon</item_description>

<option id=0 name="Assault Rifle">
<engine_action>set player_pri_weapon 0</engine_action>
<description>The player's primary weapon will be an assault rifle</description>
</option>

<option id=1 name="Pistol">
<engine_action>set player_pri_weapon 1</engine_action>
<description>The player's primary weapon will be a pistol</description>
</option>
</item>

<item id=1 name="Secondary Weapon" exclusive_with_item_id=0>
...
</item>

<item id=2 name="Example Child Menu" child_menu_id=3>
<description>Opens a child menu to change more stuff</description>
</item>
</menu>


<menu id=3 name="Example Child Menu" return_menu=0 return_item=2>

<item id=0 name="Gravity">
<item_description>Adjust world gravity</item_description>

<option id=0 name="50%">
<engine_action>physics_set_gravity 0.5</engine_action>
<description>Gravity will be 50% of normal strength</description>
</option>

<option id=1 name="100%">
<engine_action>physics_set_gravity 1</engine_action>
<description>Gravity will be normal strength</description>
</option>
</item>


</menu>
</mcc_menu>
```

This would be a powerful tool for modders to allow the player to choose customisation.

### Reproduction steps

N/A

### How often does the issue occur?

Once

**Comment by General-101** [comment]
Modding the UE4 UI is out of scope. Closing
