### ISSUE TITLE
H2AMPEK: Add support for campaign maps, like ODST has support for Multiplayer

### ISSUE THREAD

**Issue by DFlogFlag** [Joint-Issue-Tracker/Joint-Issue-Tracker#126]
### Issue type: Is this a bug or feature request?

Feature request

### Which game's editing kit is affected by the issue?

H2AEK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [ ] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [X] In-game (MCC)

### Issue description

Some people have been able to create and compile campaign maps in the H2AMPEK but in Excession there is no campaign option and neither in the MCC, therefore it is impossible to load H2AMPEK campaign maps in the MCC
For Halo 3 ODST they added multiplayer mod support, the same should be done with the H2AMPEK for campaign

### Reproduction steps

-No campaign options for Halo 2AMP on Excession
-No campaign menu for Halo 2AMP on MCC
-No campaign for Halo 2AMP :(

### How often does the issue occur?

100%

### Issue impact

The Halo 2AMP engine is supposed to be the best for being the newest, but since you can't upload campaign maps hardly anyone makes mods Halo 2AMP.
Adding campaign map support for Halo 2AMP will make more people try it, it can also be said that it has several advantages over the Halo 4 mods tools, since it supports dual wielding, elite preferred especies, pbr shaders and etc by default.

**Comment by General-101** [comment]
Out of scope for the MCC project. Closing
