### ISSUE TITLE
LODs are not separated

### ISSUE THREAD

**Issue by DG5312** [Joint-Issue-Tracker/Joint-Issue-Tracker#13]
### Issue type: Is this a bug or feature request?

Feature request

### Which game's editing kit is affected by the issue?

H2EK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [ ] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [X] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] In-game (MCC)

### Issue description

The LODs are not separated by file but come all in one, could be nice have LODs without having to separate them manually.
It also happens in H3EK

![image](https://user-images.githubusercontent.com/99689021/186564910-b1c8a29e-2768-4a69-bcdd-152f5df630b7.png)

and with wireframe (for see the mess)

![image](https://user-images.githubusercontent.com/99689021/186565024-82cc61da-0ba1-45d7-8763-1837e045dffd.png)

### Reproduction steps

Extract a render_model, the crate space
tool extract-render-data "objects\gear\covenant\military\crate_space\crate_space"

Open the model and you see.

i got this model of tool
https://cdn.discordapp.com/attachments/741351283083968586/1012192564771827762/crate_space.jms

### How often does the issue occur?

100%

### Issue impact

The workaround more useful is use DaeConverter, this drop .obj files (with broken rotations in blender 3.2.2 but works).
https://github.com/Project-Cartographer/DaeConverter

### Additional comments

H2EK and H3EK need this and if in a future HCEEK get an update for extract models would need this too.

**Comment by General-101** [comment]
Commands like extract-import-info and extract-render-data do not rip the processed model data. They give you the compresses import file stored in the tag if it has it. You're getting the exact file as it was when the original author imported it. Tool is not reading or generating a JMS file. 

Closing this due to the above. This isn't really an actionable request without an entirely different system.
