### ISSUE TITLE
Screenshot commands don't work properly with post processing (DOF, Letterbox etc)

### ISSUE THREAD

**Issue by ghost** [Joint-Issue-Tracker/Joint-Issue-Tracker#15]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

H3EK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [X] Sapien (`sapien.exe`)
- [X] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] In-game (MCC)

### Issue description

The screenshot console commands don't work properly with post processing effects such as letterboxes, depth of field and others, the frame is duplicated and tiled over the final image (the tiled image count depends on how large the resolution is, the larger your resolution the more the image is duplicated)

This seems to happen regardless of resolution, aspect ratio or command

720p:
![720p](https://user-images.githubusercontent.com/77096039/187262467-25d9157e-c737-435b-a8fa-a3fdb09676d3.png)

1080p:
![1080p](https://user-images.githubusercontent.com/77096039/187262477-2587545a-ad8d-4a1b-8df4-ce3434b3bab3.png)

1080p Ultrawide:
![1080puhd](https://user-images.githubusercontent.com/77096039/187262499-0f70f904-e8a9-4235-9a8a-6709a51bc1d8.png)

### Reproduction steps

1. Activate any post processing effect (I used render_depth_of_field_enable)
2. Take a screenshot using one of the screenshot commands (I used screenshot)

### How often does the issue occur?

100%

**Comment by General-101** [comment]
Confirmed

**Comment by kornman00** [comment]
This should be resolved in the 2023/07/12 update.
