### ISSUE TITLE
Rescaling the debug menu

### ISSUE THREAD

**Issue by ghost** [Joint-Issue-Tracker/Joint-Issue-Tracker#19]
### Issue type: Is this a bug or feature request?

Feature request

### Which game's editing kit is affected by the issue?

H3EK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [X] Sapien (`sapien.exe`)
- [X] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

The ability to scale the debug menu would be great.

After the August update it's been changed to scale with resolution which makes the debug menu extremely big and even unusable on a ultrawide display if the menu includes a bunch of options (debug, cheats).

Cheats:
![unknown](https://user-images.githubusercontent.com/77096039/188236796-dd1eb0d3-d33e-4b13-876d-08ac30d56bc2.png)

Debug:
![unknown](https://user-images.githubusercontent.com/77096039/188236917-fd0ca8ee-d39d-4741-9842-47acc7cc34a0.png)

### Reproduction steps

N/A

### How often does the issue occur?

100%

**Comment by kornman00** [comment]
How do you feel about this? This is after updating the scaling code to use the same scalar logic as used in text scaling in various debug text (and I think in other areas). Vertical resizing images to follow in a separate reply
![Aligned scaling Main page](https://user-images.githubusercontent.com/1270047/188576280-d6740269-396d-448d-8075-cfc758d8f0cf.png)
![Aligned scaling Debug subpage](https://user-images.githubusercontent.com/1270047/188576825-014cb6a5-e6a8-43c3-9b32-4f47f3b1f0f5.png)

**Comment by kornman00** [comment]
Vertical resizing behavior:
![unknown](https://user-images.githubusercontent.com/1270047/188577004-bd268760-ad24-49e7-a015-201841d1017b.png)
![unknown](https://user-images.githubusercontent.com/1270047/188577021-2d7b382d-9dee-4371-bffa-c26426507d71.png)
![unknown](https://user-images.githubusercontent.com/1270047/188577033-e01c7834-6b47-4d66-9899-04c76b53c0eb.png)
![unknown](https://user-images.githubusercontent.com/1270047/188577053-805227f6-bd83-4000-8d7e-ec2ed88cee3b.png)

**Comment by Kashiiera** [comment]
Looks much better

**Comment by kornman00** [comment]
Except this to be fixed in H3/ODST/Reach in the next tools update

**Comment by kornman00** [comment]
Those changes are in the latest update
