### ISSUE TITLE
Working with AI Objectives causes crashes

### ISSUE THREAD

**Issue by ghost** [Joint-Issue-Tracker/Joint-Issue-Tracker#21]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

H3EK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [X] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

Doing anything with AI Objectives (creating, editing, etc..) causes a crash randomly with this error:

```
09.02.22 23:55:42.313 0050052 g001574 f0060711  -FATAL- sapien  test x64 untracked version  Aug 21 2022 17:25:20 
09.02.22 23:55:42.313 0050053 g001574 f0060711  -FATAL- ### ASSERTION FAILED:  at e:\jenkins\workspace\mcch3code-release\mcc\release\h3\source\sapien\ai_objectives_view.cpp,#3177 
09.02.22 23:55:42.314 0050054 g001574 f0060711  -FATAL-   area_ref.zone_index==objective->zone_index
```

### Reproduction steps

Edit / Create any AI Objective

### Debug logs

[crash_info.txt](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/files/9483041/crash_info.txt)
[debug.txt](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/files/9483045/debug.txt)

### How often does the issue occur?

100%

### Issue impact

Making anything surrounding AI Objectives is basically impossible

**Comment by Krevil** [comment]
Fixed in December update
