### ISSUE TITLE
Not implemented for d3d11 Bug

### ISSUE THREAD

**Issue by HarbingerInfinit** [Joint-Issue-Tracker/Joint-Issue-Tracker#26]
### I confirm this not a toolkit issue but an issue relating to the bug tracker itself.

Confirm

### Issue

e:\jenkins\workspace\mccreachcode-release\mcc\release\reach\shared\engine\source\omaha\tool\geometry\render_geometry\strippers\render_geometry_stripper_wrappers.cpp(646): assert_handle_slim_constant :: not implemented for d3d11
reach tool test x64 untracked Aug 31 2022 11:56:52
### ASSERTION FAILED: at e:\jenkins\workspace\mccreachcode-release\mcc\release\reach\shared\engine\source\omaha\tool\geometry\render_geometry\strippers\render_geometry_stripper_wrappers.cpp,#646
  not implemented for d3d11
crash: beginning stack walk (code map '.\bin\tool_test.map' not found)
automation: halt and catch crash
lifecycle: CRASH
crash: fatal error detected, current status was:
crash:     command line argument: tool.exe import characters\halo3elite\halo3elite.sidecar.xml
crash:     session_id: Thu_09 82022_154500@x64@Harbinger@MSI
crash:     sound: init done
crash:     using 1GB mode: N/A
crash:     system_milliseconds: time 86203
crash:     timezone_seconds_offset_from_UTC: 18000

Not sure what is the cause of this.

**Comment by Krevil** [comment]
Should have used the issue form for the kits rather than the one for this repository

**Comment by kornman00** [comment]
Should be fixed in a future update

**Comment by kornman00** [comment]
This should be resolved in the 2023/07/12 update.
