### ISSUE TITLE
Can't compile scripts, crashes

### ISSUE THREAD

**Issue by kaboose1066** [Joint-Issue-Tracker/Joint-Issue-Tracker#29]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

H3EK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [X] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

sapien crashes whenever I run scripts, occasianally it will let me compile once, but then crash the next time...wasn't an issue on older versions.

### Reproduction steps

compile any scripts

### Debug logs

09.11.22 21:04:51.865 0009873 g001642 f0001629  -FATAL- design:hs: [mia_mission line 394] this is not a valid cutscene_flag name: nav_canyon_exit")
 
09.11.22 21:04:51.880 0009874 g001642 f0001629  -FATAL- design:hs: Stripping script camp_3_canyon 
09.11.22 21:04:51.996 0009875 g001642 f0001629  -FATAL-  
09.11.22 21:04:52.000 0009876 g001642 f0001629  message crash: beginning stack walk (code map '.\bin\sapien_test.map' not found) 
09.11.22 21:04:52.000 0009877 g001642 f0001629  -FATAL-  
09.11.22 21:04:52.003 0009878 g001642 f0001629  -FATAL- sapien  test x64 untracked version  Aug 21 2022 17:25:20 
09.11.22 21:04:52.010 0009879 g001642 f0001629  -FATAL- ### ASSERTION FAILED:  at e:\jenkins\workspace\mcch3code-release\mcc\release\h3\source\sapien\multiselect_update_object.cpp,#169 
09.11.22 21:04:52.017 0009880 g001642 f0001629  -FATAL-   IN_RANGE_INCLUSIVE(offset, 0, element_size) 
09.11.22 21:04:58.156 0009881 g001642 f0001629  WARNING lifecycle: CRASH 
09.11.22 21:04:58.160 0009882 g001642 f0001629  message crash: fatal error detected, current status was: 
09.11.22 21:04:58.160 0009883 g001642 f0001629  message crash:     session_id: Sun_09112022_210319@x6@Daniel@DANIEL-PC 
09.11.22 21:04:58.160 0009884 g001642 f0001629  message crash:     sound: init done 
09.11.22 21:04:58.160 0009885 g001642 f0001629  message crash:     map: loaded levels\solo\02_mia\02_mia 
09.11.22 21:04:58.160 0009886 g001642 f0001629  message crash:     game_instance: 49AE9D53DCD2445B 
09.11.22 21:04:58.160 0009887 g001642 f0001629  message crash:     game_simulation: local 
09.11.22 21:04:58.160 0009888 g001642 f0001629  message crash:     game_playback: none 
09.11.22 21:04:58.160 0009889 g001642 f0001629  message crash:     zone_set: switched to #0 ('dunes') 
09.11.22 21:04:58.160 0009890 g001642 f0001629  message crash:     designer_zone: switching to 0x0 () 
09.11.22 21:04:58.160 0009891 g001642 f0001629  message crash:     cinematic_zone: switching to 0x0 () 
09.11.22 21:04:58.160 0009892 g001642 f0001629  message crash:     bsp: initialization done 0x1f (bsp02, bsp01, bsp05, bsp03, bsp04) 
09.11.22 21:04:58.160 0009893 g001642 f0001629  message crash:     minor_version: -1 
09.11.22 21:04:58.161 0009894 g001642 f0001629  message crash:     last_tag_sync: time 2 
09.11.22 21:04:58.161 0009895 g001642 f0001629  message crash:     system_milliseconds: time 100698 
09.11.22 21:04:58.163 0009896 g001642 f0001629  message networking:online:lsp: entering crash mode 
09.11.22 21:04:58.163 0009897 g001642 f0001629  message networking:online:lsp: resetting 

### How often does the issue occur?

100%

### Issue impact

can't update mods or make new ones

### Additional comments

kinda high priority

**Comment by Lord-Zedd** [comment]
Did you confirm that fixing this didn't solve the crash?
`[mia_mission line 394] this is not a valid cutscene_flag name: nav_canyon_exit")`

**Comment by kaboose1066** [comment]
Yes, after fixing it, happens also, occasionally it will compile fine, 50
50.

**Comment by kornman00** [comment]
that assert should be fixed in latest
