### ISSUE TITLE
.pixel_shader compatibility issue

### ISSUE THREAD

**Issue by FaberTheCatgirl** [Joint-Issue-Tracker/Joint-Issue-Tracker#3]
# Workaround!
For anyone else that runs into this issue you can delete the automatically generated pixel and vertex shader files, and regenerate them using the steps listed here https://c20.reclaimers.net/h3/compiling-shaders/#regenerating-templates

### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

H3ODSTEK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [X] Sapien (`sapien.exe`)
- [X] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] In-game (MCC)

### Issue description

Halo 3 .scenario and .scenario_structure_bsp tags will fail to load due to an issue with compatibility in the .pixel_shader and other shader tags from Halo 3

Issues tend to appear in individual tags such as shaders\cortana_templates\_0_0_1_0_2_0_0_0_0.pixel_shader

Please note that this issue currently affects the entirety of the ODSTEK.

### Reproduction steps

Copy the tags from a Halo 3 solo level with all its required tag dependencies, then load the scenario in Tag Test or Sapien

### Debug logs

[crash_info.txt](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/files/8910306/crash_info.txt)
[crash_info.txt](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/files/8910391/crash_info.txt)

### How often does the issue occur?

100%

### Issue impact

This issue impacts any creators looking to port their created content and assets between ODST/H3

### Additional comments

This possibly could be resolved with a patch to Tool's shader generator

**Comment by num0005** [comment]
I could see the case for the expected behavior being something other than a hard crash.

**Comment by num0005** [comment]
For anyone else that runs into this issue you can delete the automatically generated pixel and vertex shader files, and regenerate them using the steps listed here https://c20.reclaimers.net/h3/compiling-shaders/#regenerating-templates

**Comment by FaberTheCatboy** [comment]
That Solution worked for me, Thanks @num0005
