### ISSUE TITLE
[HREK] print-tag-to-xml error "Input tag path is not located in the tags directory structure"

### ISSUE THREAD

**Issue by GoomiiV2** [Joint-Issue-Tracker/Joint-Issue-Tracker#35]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

HREK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [ ] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [X] Tool (`tool.exe`)
- [X] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

The ``print-tag-to-xml`` command doesn't seem to work, each time i try to use it I get the error
```Input tag path is not located in the tags directory structure``` even when the tag path is under the tags dir.

I have tried both of these commands and got the same error
```
tool.exe print-tag-to-xml "D:\Games\Steam\steamapps\common\HREK\tags\levels\solo\m20\shaders\carbon_fiber_panels_damaged.shader"
```
and
```
tool.exe print-tag-to-xml "levels\solo\m20\shaders\carbon_fiber_panels_damaged.shader"
```

How ever the ``export-tag-to-xml`` works just fine with the full tag path like
```
tool.exe export-tag-to-xml "levels\solo\m20\shaders\carbon_fiber_panels_damaged.shader" test.xml
```

Extra:
The Halo 3 tool builds ``print-tag-to-xml`` works just fine on this tag with the full path.

### Reproduction steps

Run the command

```
tool.exe print-tag-to-xml "D:\Games\Steam\steamapps\common\HREK\tags\levels\solo\m20\shaders\carbon_fiber_panels_damaged.shader"
```

With ``D:\Games\Steam\steamapps\common\HREK\tags`` being your tags path ofc.

### Debug logs

NA

### How often does the issue occur?

100%

### Issue impact

Over all I'd class it as minor as the ``export-tag-to-xml`` does work and I can use that as a work around.

**Comment by kornman00** [comment]
Ha. Would help if I actually constructed the filename string using the arg 
![image](https://user-images.githubusercontent.com/1270047/190490681-06a5a6ab-04e9-43a2-b6b6-2d67b2c0709a.png)

**Comment by kornman00** [comment]
should be fixed in latest
