### ISSUE TITLE
MegaloEdit autocomplete box blocks text if suggestion isn't picked while not scrolled to the bottom of the script

### ISSUE THREAD

**Issue by Unfunkable** [Joint-Issue-Tracker/Joint-Issue-Tracker#37]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

HREK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [ ] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [X] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

If the autocomplete box is open, and you were to continue typing instead of picking a suggestion, the autcomplete box will slowly raise over text for every character typed. However, if scrolled to the bottom of the document, this does not occur.

https://user-images.githubusercontent.com/73909698/190883906-ada4ea2d-245e-4a4e-92a9-69fc03f4c765.mp4

### Reproduction steps

1. Open any gametype which requires scrolling to view the entire script
3. Press Ctrl+Space or `.` to invoke the autocomplete box
4. Continue typing rather than picking a suggestion

### How often does the issue occur?

100%

### Issue impact

Quite inconvenient but can be worked around by clicking a different line to close the box. The box comes up frequently, so this has to be done multiple times.

**Comment by Unfunkable** [comment]
Added some more info, this does not occur if you have scrolled to the bottom of the script, but does otherwise.

**Comment by kornman00** [comment]
I've fixed this, should be present in any future updates

**Comment by kornman00** [comment]
This should be resolved in the 2023/07/12 update.
