### ISSUE TITLE
Can't copy .biped without it breaking character movement

### ISSUE THREAD

**Issue by kaboose1066** [Joint-Issue-Tracker/Joint-Issue-Tracker#38]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

H3EK

### Which tools are affected by the issue?

- [X] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [x] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

Hard to explain, I have a new sentinel varient with custom animation graph (sentinel protector). I originally copied the aggressors .biped tag as a base, but in sapien once spawned it wouldn't move, just floats there still as ice. But if I switch the .biped in the .character tag to the aggressor.biped tag it acts like a normal aggressor...If I then switch the aggressors .model tag inside of the aggressors .biped tag to my new protector.model, my protector suddenly acts normal with all it's custom animations just fine. HOWEVER this is using the vanilla original aggressors .biped tag, so I copied the aggressors .biped tag again adn set it up exactly the same but now it's a copy and not the original tag (because then I wouldn't be able to use the aggressor anymore, since it was changed to be the protector), but no, it doesn't move at all. I also tried copying the entire aggressor folder tag, and then take that .biped tag, but no, no movement. Conclusion, I can't use the aggressors .biped tag unless I use the VANILLA ORIGINAL one, any copies of it breaks everything, even though it's the exact same setup, if you understand me. Here's a video of the issue: https://youtu.be/pJWypY6kpio

### Reproduction steps

watch video in issue description

### Debug logs

no errors for anything related

### How often does the issue occur?

100%

### Issue impact

can't create new enemy varient, would have to overwrite original aggressor

**Comment by Krevil** [comment]
You need to give the new sentinel biped a vehicle properties block in the character tag. I would suggest duplicating the aggressor entry in the generic character and setting the unit to your new biped.

**Comment by kaboose1066** [comment]
> You need to give the new sentinel biped a vehicle properties block in the character tag. I would suggest duplicating the aggressor entry in the generic character and setting the unit to your new biped.

oh my gosh, it was that easy huh, was on this error for 4 hours... thanks, can delete this thread, though it's not clear that needs to happen since theres no reference to it in the aggressor tags anywhere that I saw?
