### ISSUE TITLE
Adding a new entry in the animations box in a model_animation_graph crashes Foundation.

### ISSUE THREAD

**Issue by TheVengefulVadam** [Joint-Issue-Tracker/Joint-Issue-Tracker#39]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

HREK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [X] Foundation (`Foundation.exe`)
- [ ] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

Adding a new Animation entry via the model_animation_graph will cause an exception to occur, hard-crashing Foundation.

### Reproduction steps

Add an entry to the animations block in a model_animation_graph, then attempt to save. 

### Debug logs

[crash_info.txt](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/files/9603423/crash_info.txt)
[debug.txt](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/files/9603424/debug.txt)

### How often does the issue occur?

100%

### Issue impact

This affects animation inheritance in a way. Animation inheritance normally works fine if you set the parent animation graph to another animation, then set the graph index to whatever animation you want. However, I'd like to make duplicates of certain animations to have different effect/sound events, and these crashes make that impossible.

**Comment by General-101** [comment]
Animation Inheritance is done by tool. Not by Guerilla or Foundation. You aren't supposed to be doing these things manually

**Comment by General-101** [comment]
Marking this as a won't fix due to the feature not being supported in the first place. Keep in mind that if the thing you are doing requires expert mode then you are not meant to be doing what you're doing.
