### ISSUE TITLE
Overlay Animations that use Blend Screens are Bugged in HREK

### ISSUE THREAD

**Issue by GreenKnight5417** [Joint-Issue-Tracker/Joint-Issue-Tracker#53]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

HREK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [X] Foundation (`Foundation.exe`)
- [X] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [X] Tool (`tool.exe`)
- [X] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [X] In-game (MCC)

### Issue description

Overlay animations related to aiming or steering do not function and seem to be bugged. 

### Reproduction steps

The only way I have been able to get these overlay animations to work is by doing this:
1. Use the legacy format (JMS/JMA)
2. Import an animation graph with the steering animation, setup new overlay groups and anything else needed.
3. Import animations again but WITHOUT the steering animation.
4. Import animations again but WITH the steering animation and set it up in new overlay groups again.

Otherwise this issue occurs 100% of the time.

After essentially importing it twice it starts working. This does not work for the newer GR2 format.

### How often does the issue occur?

100%

### Issue impact

Workaround was stated above. This breaks any custom imported vehicles or bipeds because they cannot have aiming/steering animations.

### Additional comments

Some people have said this is because of the FBX-GR2 command, but nothing has been proven.

**Comment by Krevil** [comment]
Closed upon request.
