### ISSUE TITLE
Reusing Existing Animation Graphs in HREK cause Improper Rotations

### ISSUE THREAD

**Issue by GreenKnight5417** [Joint-Issue-Tracker/Joint-Issue-Tracker#54]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

HREK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [X] Foundation (`Foundation.exe`)
- [X] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [X] Tool (`tool.exe`)
- [X] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [X] In-game (MCC)

### Issue description

![uhhhhh](https://user-images.githubusercontent.com/109719971/195970755-88639fb4-9335-4d30-9492-29527d2ac055.PNG)

The skeleton for the elite was ripped using Reclaimer. As you can see there is a big issue here. This applies to reusing any skeletons/animation graphs.

### Reproduction steps

Rip an existing skeleton from Reach using any method. Give your biped or vehicle the animation graph for the skeleton you ripped and this will always happen. Using a parent animation graph does not fix the issue.

### How often does the issue occur?

100%

### Issue impact

Reusing animations is impossible due to this issue. This means that thousands of existing animations cannot be used and if you wanted to do something such as replace your player but reuse the animations/skeleton you can't. 

This was not an issue in Halo 3 and many people took advantage of this.

**Comment by General-101** [comment]
Solved
