### ISSUE TITLE
HREK FBX-to-GR2 Instances seemingly dont get converted correctly (size bloat+import errors)

### ISSUE THREAD

**Issue by ivanivanovitch** [Joint-Issue-Tracker/Joint-Issue-Tracker#58]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

HREK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [ ] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [X] Tool (`tool.exe`)
- [X] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

Converting an FBX with instances (using a 3rd party blender exporter that does support Instancing in FBX files since blender exporter natively does not) causes the GR2 file to dramatically bloat in size (4MB.fbx > 300mb.gr2) this also makes the import process extremely slow with alot of instances since tool treats every single instance as a new definition despite being the same instanced object. this also extremely limits the amount of instances you can have since tool reads every instance as a new definition quickly hitting the 1024 definition limit for a bsp. the weird part is once everything does import every instance in sapien reads back the correct definition despite having all of the definitions written to the structure bsp tag. so im assuming the GR2 conversion does not properly write instances but instead writes them as regular meshes.
![image](https://user-images.githubusercontent.com/25913863/196048679-7ba480f9-c876-4471-8924-9c0326412b47.png)
![image](https://user-images.githubusercontent.com/25913863/196048693-fcd7b6af-8598-4e97-bd8d-28a92f616028.png)
Example images of an FBX file with instancing bloating heavily when converted
![explorer_yUyydGkAN8](https://user-images.githubusercontent.com/25913863/196048730-7d85d8ae-7b12-48eb-9b69-febde5a68511.png)
example of a tool material error showing every new rock instance writing as a new definition in the structure BSP.

### Reproduction steps

- Export a scene with an object instanced
- set up the .JSON for the FBX (this one was automated by discord user: Crisp#3041's blender plugin)
![image](https://user-images.githubusercontent.com/25913863/196048904-eac6fb82-5a7c-4ea6-b72a-8445daa5e13c.png)
- import your sidecar
- wait an eternity for tool to process every single instance as a new object
- receive bloated structure bsp tag

### How often does the issue occur?

100%

### Issue impact

This is a massive issue for custom mapping in halo reach and will severely limit the amount of detail a map creator can put in due to hitting the definition limit in about 1K instances total.

**Comment by General-101** [comment]
The unlinked instance part of this ticket has been solved.

As the bloating part is more related to the exporter rather then tool itself I'm considering this issue solved.
