### ISSUE TITLE
[HCEEK] Request: add one or two bitmap import flags to assist with re-importing textures at higher quality.

### ISSUE THREAD

**Issue by Aerocatia** [Joint-Issue-Tracker/Joint-Issue-Tracker#59]
### Issue type: Is this a bug or feature request?

Feature request

### Which game's editing kit is affected by the issue?

H1EK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [ ] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [X] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

There are format-specific behaviours that many textures in *Halo* depend on to look correct.
This means that to re-import these textures at higher quality (e.g. 32-bit) , you have to do a lot of manual editing so they are functionally the same. If #56 ever gets implemented, the same issues are going to apply for that too if we want to re-import everything as BC7.

Adding a couple of bitmap import options would allow re-importing the textures to any format to be possible while keeping the original source data in tact. 

### Option 1: "one bit alpha"
This option would force DXT1/BC1 alpha behavior on any format. This would mean alpha of `0` would be transparent, while `>=1` would become `255` Some textures in *Halo* depend on this to look correct in game. Rather than manually crunching the alpha in an image editor for every affected texture we could instead set this option if the current format of the tag is BC1.

### Option 2: "zero alpha is opaque"
This option would define the bug #50 as a feature, applying across all formats. This means `0` alpha across *every* pixel would mean that bitmap should be imported as completely opaque, otherwise alpha should be preserved as-is. Note the every pixel part, if there is even one non-zero alpha pixel in the bitmap then alpha should be preserved.

Many lossless bitmaps depend on this behavior to work, as they have `0` alpha and are not intended to be transparent. On the other hand, there are other bitmaps that have `0` alpha and *do* need to remain transparent. The only way to import everything as the same format without manual editing is to make this an option.

There is even a BC1 texture that depends on this. (`levels\b30\bitmaps\dirt splotch detail`)
Given current versions of tool.exe do not do this when importing as BC1, it is impossible to import this again unmodified. Maybe BC1 behavior changed since this was made?

### Reproduction steps

Example 1:
Importing `levels\b40\bitmaps\b40_ctrlglass` as 32-bit will break because it depends on #50 being fixed to work.

Example 2:
If you re-import `vehicles\scorpion\bitmaps\headlight_lens_flare` as BCn it will break because it depends on #50 happening to work and #50 only applies to lossless textures.

Example 3:
The texture `levels\b40\devices\b40_outerdoor\bitmaps\b40_doorlock` depends on BC1 alpha, if you re-import this as 32-bit the doors will break and be transparent when they are not meant to be.

### Debug logs

N/A

### How often does the issue occur?

100%

### Issue impact

Bitmap import behavior is inconsistent across formats, it would be nice if each format imported in a consistent way and legacy quirks are re-implemented as controllable features.

### Additional comments

While we can account for this in unofficial tools like invader, not having the desired behivior defined in tag data would make it a nightmare to use. Ideally this should be upstream.

**Comment by Vaporeon** [comment]
I went through every stock bitmap in the game to see what would be affected by #50's bug/behavior
Here is what I found would need changed for the bitmaps to be functionally the same.

### Breaks if alpha 0 not set to 255:
Currently broken on some formats (#50)
```
effects\particles\lens flare\bitmaps\flares_generic.bitmap
levels\b40\bitmaps\b40_fog_noise.bitmap
levels\c10\bitmaps\fog_noise.bitmap
rasterizer\vector normalization.bitmap
scenery\halo_destroyed\bitmaps\halo_explosion_flares.bitmap
vehicles\scorpion\bitmaps\headlight_lens_flare.bitmap
vehicles\warthog\bitmaps\headlight flares.bitmap
levels\b30\bitmaps\dirt splotch detail.bitmap
```


### Breaks if alpha >1 not set to 255:
Some of these look like they should be DXT3, see comments. others outright break as anything other than DXT1.
```
levels\a50\bitmaps\covenant cor floor.bitmap # was this intened to be dxt3 (and keep alpha)?
levels\a50\bitmaps\covenant plasma streams.bitmap # see above, dxt1 is wiping color it should not be.
levels\d40\bitmaps\lt steel.bitmap # see above
levels\test\gephyrophobia\bitmaps\geph_metalpanels_generic.bitmap # see above
levels\test\tutorial\bitmaps\example_tutorial_metal.bitmap # see above
levels\test\tutorial\bitmaps\example_tutorial_panels.bitmap # see above, breaks on current tool.exe (rightly so)
levels\test\tutorial\bitmaps\example_tutorial_plate_floor.bitmap # see above

levels\b40\devices\b40_outerdoor\bitmaps\b40_doorlock.bitmap # breaks b40/c40 doors if alpha is kept (anything but dxt1).

levels\test\infinity\bitmaps\infinity sign blue glow.bitmap # Gearbox in charge of making glow maps.
levels\test\infinity\bitmaps\infinity sign red glow.bitmap # this is the same bitmap!
```

### Breaks if not imported as completely transparent:
Currently broken on some formats (#50)
```
levels\b40\bitmaps\b40_ctrlglass.bitmap
levels\test\timberland\scenery\simple_beacon_red\bitmaps\simple_beacon_red_marker.bitmap
levels\test\timberland\scenery\simple_beacon_blue\bitmaps\simple_beacon_blue_marker.bitmap
ui\shell\bitmaps\list_item_bkd.bitmap
ui\shell\bitmaps\list_item_bkd_top.bitmap
ui\shell\bitmaps\sel_list_item_bkd.bitmap
ui\shell\bitmaps\sel_list_item_bkd_top.bitmap
ui\shell\bitmaps\loc_menu_bkds.bitmap
ui\shell\bitmaps\loc_menu_bkds_sm.bitmap
ui\shell\bitmaps\locked_gametype.bitmap
ui\shell\main_menu\multiplayer_type_select\join_game\classic_icon.bitmap
ui\shell\main_menu\multiplayer_type_select\join_game\dedicated_icon.bitmap
ui\shell\main_menu\multiplayer_type_select\join_game\locked_icon.bitmap
weapons\sniper rifle\bitmaps\angle_ticks_black.bitmap
```

**Comment by Aerocatia** [comment]
Maybe I'll close this, it is probably better to just fix the source data anyway. The import bugs still apply though.

**Comment by Aerocatia** [comment]
Better to just fix the tiffs
