### ISSUE TITLE
[H3EK] tags rebuilt/recompiled with tool are not reloaded in Standalone

### ISSUE THREAD

**Issue by Markelius** [Joint-Issue-Tracker/Joint-Issue-Tracker#61]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

H3EK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [ ] Sapien (`sapien.exe`)
- [X] Standalone (`halox_tag_test.exe`)
- [X] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

What it says in the title. Tags rebuilt/recompiled by Tool are not reloaded by Standalone. For me this happens with .multilingual_unicode_string_list tags that have been compiled using the strings command, .bitmap tags (clicking "Reimport Bitmap" inside Guerilla seems to be affected less often), as well as importing .render_model, .collision_model, and .physics_model tags. It is possible more tags created/modified/overwritten by tool are affected by this but I have only listed the ones I know of.

### Reproduction steps

- Rebuild loaded tag with tool.exe
- tag is not reloaded as expected

### How often does the issue occur?

75%

### Issue impact

This greatly impacts my workflow as often the only way to have the changes reflected is to completely close and relaunch Standalone, adding minutes to each iteration where they would have otherwise only taken seconds.

Workarounds do exist but are unreliable, sometimes not working at all, the only foolproof solution is to relaunch Standalone completely.

For bitmap tags, often editing the .shader tag in Guerilla that refers to the bitmap tag can cause the bitmap to reload. Particularly by pointing to a different bitmap, saving the shader and allowing Standalone to reload the shader, then editing it again and pointing it to the original bitmap, saving it once more. This is fairly reliable but sometimes will not work.

Editing the bitmap tag itself in Guerilla by changing the import settings and saving can also cause Standalone to reload the tag, sometimes this does not work and has to be done multiple times.

For .render_model, .physics_model, and .collision_model tags, sometimes editing the tags in Guerilla and saving them can cause them to be reloaded in Standalone, I recommend changing unimportant things such as unused flags so as not to cause issues ingame. Editing the .model tag which refers to these tags and the tags themselves at the same time can also cause Standalone to reload them, but is unreliable and sometimes inapplicable (i.e. for first-person weapon models).

No known dedicated solutions exist for forcing Standalone to reload .multilingual_unicode_string_list tags.

Sometimes causing a map reload or returning to main_menu.map and reloading the map you were in can cause any and all tags mentioned to reload, but this is time consuming and also unreliable, if the above methods didn't work, it's often easier to give up and relaunch Standalone.

### Additional comments

Adding a command in Sapien and Standalone to reload a specific tag, perhaps with the same syntax as the drop command, would be a great workaround for when issues like this.

**Comment by kornman00** [comment]
This is likely an artifact of your anti-virus software. Ensure your tools install directories (or at the very least your data and tags folders) are excluded from active monitoring.

**Comment by Markelius** [comment]
> This is likely an artifact of your anti-virus software. Ensure your tools install directories (or at the very least your data and tags folders) are excluded from active monitoring.

I set up excludes for data and tags and that seems to have fixed it so far, wow! This has been an issue for me for over a year and no one has suggested this to me, thanks!

**Comment by Krevil** [comment]
Closing this since the issue has been resolved.
