### ISSUE TITLE
Feature Request: Undo / Redo for H3EK Sapien

### ISSUE THREAD

**Issue by R93Sniper** [Joint-Issue-Tracker/Joint-Issue-Tracker#7]
### Issue type: Is this a bug or feature request?

Feature request

### Which game's editing kit is affected by the issue?

H3EK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [X] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] In-game (MCC)

### Issue description

Placement of objects in sapien can generally be finnicky when trying to move them with the handles. Trying to select an object from the game window will sometimes also force them to get sent to the first piece of level geo that can be collided. As a general QOL request: allow us to have an undo/redo buffer. Ideally let us choose how many steps back it can go, but a minimum for an immutable amount should be 25.

### Reproduction steps

N/A

### How often does the issue occur?

75%

### Issue impact

Can severely slow down the placement of objects in sapien if they need to be precisely aligned. This is worse if the object is in the air

### Additional comments

High preference to letting us have a settings/option menu that lets us choose how many steps we can go back to. While I understand this may not be possible, it would make things a lot easier for the end user.
If this cannot be delivered on, then at minimum we should be allowed 25 revisions.

**Comment by kornman00** [comment]
This is outside of the scope of any potential work that would be considered for any game's sapien
