### ISSUE TITLE
[H1EK] Standalone crashes in MP scenarios when pressing melee and reload simultaneously on picked-up weapons

### ISSUE THREAD

**Issue by arcdluna** [Joint-Issue-Tracker/Joint-Issue-Tracker#75]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

H1EK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [ ] Sapien (`sapien.exe`)
- [X] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

Rapidly pressing the melee and reload key while a weapon with a clip is reloading (e.g the Assault Rifle) will crash standalone in multiplayer scenarios, but only weapons that are picked up after the game starts. Weapons that the player starts with seem unaffected. Does not crash in solo. Tested with stock tags. Win 11.

### Reproduction steps

Load H1 standalone

Set the game type:
game_variant slayer

Load a multiplayer scenario:
map_name levels\test\ratrace\ratrace

Find and pick up up a weapon with a clip, spend some ammo, and then rapidly mash the reload and melee keys at the same time.

### Debug logs

[debug.txt](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/files/10200959/debug.txt)

### How often does the issue occur?

100%

### Issue impact

Low - You can simply not press reload and melee at the same time. Ideally this would be fixed though as it can easily be accidentally triggered by players who are testing weapon tags in a multiplayer scenario.

**Comment by kornman00** [comment]
Should be addressed in the next major content update

**Comment by kornman00** [comment]
This should be resolved in the 2023/07/12 update.
