### ISSUE TITLE
Lightmapper crash 

### ISSUE THREAD

**Issue by infernoplus** [Joint-Issue-Tracker/Joint-Issue-Tracker#76]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

H1EK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [ ] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [X] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

When running lightmaps for a large (world unit large not triangle count) BSP I received an unknown exception.
Running lightmaps on this exact same BSP in the old HEK works fine. 

### Reproduction steps

[desert.zip](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/files/10201120/desert.zip)

Build this jms into a bsp. Run lightmaps on it.

### Debug logs

  Using tags directory 'D:\Steam\steamapps\common\HCEEK\tags'
  Using data directory 'D:\Steam\steamapps\common\HCEEK\data'
  Using game-root directory 'D:\Steam\steamapps\common\HCEEK'
i'm going to render debug lightmaps for desert of cursed\levels\desert\desert, and i'll stop when red+blue+green = 0.644835.
Hit control-c now if this isn't right.
recompiling scripts after scenarios were merged.
start cursed\levels\desert\desert
EXCEPTION halt in e:\jenkins\workspace\mcch1code-release\mcc\release\h1\code\h1a2\sources\structures\radiosity\intermediate_radiosity.c,#890: !point_is_coplanar || _realcmp(transformed_point.z, 0.f, k_real_epsilon * 2)
EAX: 0x3D170000
EBX: 0x00000000
ECX: 0x00000000
EDX: 0x3D170000
EDI: 0x06E1CF00
ESI: 0x00000003
EBP: 0x06E1CD34
ESP: 0x06E1C950
EIP: 0x0045A618, 8B 48 04 8B ?????
77BF75C4 ?????
77BF75F4 ?????
7712FA29 ?????
00789177 ?????
004714CE ?????
EXCEPTION_ACCESS_VIOLATION

EXCEPTION (that's all I know!)
Press any key to continue . . .

### How often does the issue occur?

100%

### Issue impact

Can workaround this by using lightmaps from the old HEK.

**Comment by kornman00** [comment]
The modern tools are built with SSE2 enabled, which has a smaller precision than what the 2001-era tools had (via x87 FPU). For now, you can work around this assert by running tool with `-noassert` and see if the structure bsp works as expected.

**Comment by num0005** [comment]
Can confirm the crash, but I don't have the shaders so I can't tell if the lighting is reasonable when running with asserts disabled.

**Comment by General-101** [comment]
Closing this issue and moving it elsewhere

**Comment by num0005** [comment]
Use workaround of disabling asserts if you run into this issue.
