### ISSUE TITLE
[HCEEK] Increase model_animation units block count to match OpenSauce

### ISSUE THREAD

**Issue by Aerocatia** [Joint-Issue-Tracker/Joint-Issue-Tracker#77]
### Issue type: Is this a bug or feature request?

Feature request

### Which game's editing kit is affected by the issue?

H1EK

### Which tools are affected by the issue?

- [X] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [X] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [X] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

Open Sauce allowed 512 entries in the `units` block. Stock is limited to 32.
Increasing this would be helpful.

The other block limits were already increased in MCC CE, but for some reason `units` was left out.

### Reproduction steps

N/A

### Debug logs

N/A

### How often does the issue occur?

100%

### Issue impact

The CE default block maximum is rather limiting when wanting to support a large amount of custom objects.

**Comment by Aerocatia** [comment]
I have a model_animation tag with 66 unit blocks already, so `128` would be an ok limit if not 512.

**Comment by kornman00** [comment]
Should be addressed in the future, along with some other tweaks

**Comment by kornman00** [comment]
This should be resolved in the 2023/07/12 update.
