### ISSUE TITLE
[HCEEK] tool.exe build-cache-file can sometimes put both compressed and uncompressed model animation data in the map at the same time.

### ISSUE THREAD

**Issue by Aerocatia** [Joint-Issue-Tracker/Joint-Issue-Tracker#78]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

H1EK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [ ] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [X] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

There seems to be a condition where the `tool.exe build-cache-file` command will store both compressed *and* uncompressed animation data in the map.

Normally if a `model_animations` tag uses compressed animation data, then the uncompressed data is discarded on map build.
The expected behavior is that this happens unconditionally to all animations that use compression, however sometimes it does not.

### Reproduction steps

Prepared here in [animation-test.zip](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/files/10245639/animation-test.zip) is a heavily striped down tag (and data) that can trigger this odd behavior
The tag contains only two overlay animations, the first of these can sometimes store both types of animations data, while the second is *always* pruned in the cache build process. I am not sure why the second animation always works as expected.

1: Reference `what.model_animations` somewhere in a map so it is compiled in at build time
2: Depending on the state of the `compress all animations` import flag, one of two things will happen.

If the `compress all animations` flag *is* checked as it was when the tag was imported by the `animations` tool command,
then once built into the map animation 0 (`s-ping back gut%0`) will have BOTH compressed and uncompressed animation data in the cache file.

We can see this when using Eschaton to inspect the cache file:
![image](https://user-images.githubusercontent.com/12814075/208096194-bca11be1-754d-4b4d-b52d-c97f274c9d98.png)

We can see that default data exists and the frame data contains both compressed and uncompressed data, with the compressed data offset pointing to the start of the compressed data.

If we look at the second animation though, things are different for some reason:
![image](https://user-images.githubusercontent.com/12814075/208096603-d80f22ca-dc35-4b0c-b790-db7bbfd2db3d.png)

Here it seemed to have worked as expected, default data was removed, and frame data only contains the compressed bytes, with the uncompressed bytes being removed and the `offset to compressed data` set to `0`.

So here is where things get even more strange. If you *uncheck* the import flag `compress all animations` and immediately re-build the map (without rebuilding the animations tag) then uncompressed data is stripped for *both* animations as expected.
![image](https://user-images.githubusercontent.com/12814075/208097814-730d9c46-9c46-4ec2-ad3a-2cdb8f37e363.png)

### How often does the issue occur?

100%

### Issue impact

So the reason for concern here is that tag extractors will pad the expected uncompressed data with zeroes when extracting compressed and stripped `model_animations`.  This works because it is expected that this data will be discarded again when the tag is recompiled into a map.

The potential problem here is that if tool.exe will sometimes preserve this data then that could mean zeroed out animation data ends up compiled into maps. I'm not sure if it will even be read or how it will affect the game, but still this is a concern.

Tag extraction is a common workflow when dealing with Custom Edition content, years have past and original tags have long been lost. Ideally if the animation data is always stripped as expected when using compression, this should not be an issue.

### Additional comments

Maybe it could be an idea to have a flag in the animation flags block (under `pal 25hz`?) that can be set by tag extractors if data had to be zero-padded when re-generating the tag. There is no escaping the desire for tag extraction in the CE workflow, and having a sane way to handle this could be good.

**Comment by kornman00** [comment]
Import code checks:
`intermediate->frame_count>=MINIMUM_COMPRESSED_ANIMATION_FRAME_COUNT`
Where `MINIMUM_COMPRESSED_ANIMATION_FRAME_COUNT=6`

However, other import code ends up setting the animation's frame count to one minus the intermediate frame count:
`animation->frame_count= intermediate->frame_count-1; // overlays will remove the first frame; base and replacement animations will remove the last frame`

This then conflicts with the culling code where it checks the animation's frame count and ignores compressed animations with sub-MINIMUM_COMPRESSED_ANIMATION_FRAME_COUNT counts. So, this should be specific to animations with 6 intermediate frames only.

I'm not looking to make any changes here. You can deal with this issue by checking the animation's frame count against `MINIMUM_COMPRESSED_ANIMATION_FRAME_COUNT ` when reconstructing tags
