### ISSUE TITLE
[HCE] All custom H1 maps have a chance to crash when the level loads in MCC custom games

### ISSUE THREAD

**Issue by arcdluna** [Joint-Issue-Tracker/Joint-Issue-Tracker#79]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

H1EK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [ ] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [X] In-game (MCC)

### Issue description

This is not strictly an editing kit bug but is by proxy:
In Custom Games lobbies, all user created Halo CE maps downloaded from steam workshop have what seems to be a random chance to crash out with a UE4 error shortly after the game starts loading the level for an inconsistent number of clients. From experience, the host of the lobby typically crashes much less than clients during the initial load. Joining the game in progress does not seem to trigger this bug.

### Reproduction steps

In an MCC custom games lobby with multiple clients, select and start a custom workshop Halo CE map. During load the game will crash for some or all of the clients. The more clients in the lobby the higher the chance of seeing this crash reproduced.

### How often does the issue occur?

50%

### Issue impact

High - Many clients (occasionally *all* of them) will crash and a custom games lobby will need to be remade nearly every time a custom CE map is played, severely hampering the experience of playing them.

**Comment by kornman00** [comment]
This should be resolved in the 2023/07/12 update.
