### ISSUE TITLE
H2EK: Custom Location Names cause crash in MCC

### ISSUE THREAD

**Issue by DeadSargent** [Joint-Issue-Tracker/Joint-Issue-Tracker#81]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

H2EK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [ ] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [X] In-game (MCC)

### Issue description

In Halo 2 Classic territories, after capturing a territory you will get a message with the name of the territory you captured. The name of these locations are stored in a string list and used by the "game engine strings" parameter in a scenario tag. 

Creating a custom string list for a scenario's parameter for territory names displays those custom strings properly in TagTest. But when built into a cache file and played in MCC, the game crashes attempting to display those names.
![no ln](https://user-images.githubusercontent.com/112615362/208592231-bf478b03-32fa-435c-8b52-57c3553e6b27.png)
![with ln](https://user-images.githubusercontent.com/112615362/208592240-d241a6c4-f9c5-401d-9bf1-4d1ae8830772.png)
[location_names.txt](https:/
![proper_names](https://user-images.githubusercontent.com/112615362/208593261-5d06cfc9-3621-4440-a83c-c793a2c769ef.png)
/github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/files/10265730/location_names.txt)

### Reproduction steps

1. Create or use a scenario with territories game markers setup with indices
2. Create a custom string list with names for the territories indices. You can extract an existing location_names string list and just use it as a template for the custom names.
3. Use the custom string list for the game engine strings in the scenario
4. Build the scenario into a map file
5. Attempt to capture a territory in MCC

### How often does the issue occur?

100%

### Issue impact

Custom H2 multiplayer maps can't have custom location names for territories, so every territory captured on a custom map will just appear as "You control #territory_name"

### Additional comments

My hypothesis is that MCC fails to show it due to the negative value for the other languages in the string list. I extracted a location names string list and recompiled it with no edits and using the recompiled string list was causing crashes aswell. 

![test_strings](https://user-images.githubusercontent.com/112615362/208598153-5da63383-6d16-4523-8549-f33950118ad5.png)

**Comment by kornman00** [comment]
This should be resolved in the 2023/07/12 update.
