### ISSUE TITLE
"-ERROR- cache:resource:prediction: Raise the number of m_prediction_quanta! currently 20480" displaying incorrectly

### ISSUE THREAD

**Issue by Weaver900** [Joint-Issue-Tracker/Joint-Issue-Tracker#88]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

H3EK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [ ] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [X] Tool (`tool.exe`)
- [X] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

As far is am aware, this limit was raised in a patch for the H3EK, however occasionally tool will still give the above error using the old limit. This does not crash tool or stop the map compiling, unless it is accompanied by a second error:
"-ERROR- cache:resource:prediction: Raise the number of m_prediction_molecules! currently 8192
-FATAL-
message crash: beginning stack walk (code map '.\bin\tool_play.map' not found)
-FATAL-
-FATAL- tool  play x64 untracked version  Nov 16 2022 21:19:46
-FATAL- ### ASSERTION FAILED:  at e:\jenkins\workspace\mcch3code-release\mcc\release\h3\source\memory\wrapped_arrays.h,#71
-FATAL-   valid_index(index)
WARNING lifecycle: CRASH"
This happens quite often however, so if possible could the m_prediction_molecules possibly be raised also?

### Reproduction steps

Try to compile a map with a lot of stuff in it, but not so much stuff that you hit the prediction molecules limit.

### Debug logs

[crash_info.txt](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/files/10559846/crash_info.txt)
[debug.txt](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/files/10559850/debug.txt)

### How often does the issue occur?

100%

### Issue impact

It's very frustrating that once I hit the limit, it is very unclear what needs to be removed and what has the biggest impact on the molecule limit. Using Assembly to view what is using prediction molecules has helped, maybe it would be good to recommend this in the crash message?

**Comment by Lord-Zedd** [comment]
To clarify further, the quanta assert seems to be for 20480, but the quanta block itself has a maximum of SHORT_MAX, leading to a presumed false positive.

**Comment by kornman00** [comment]
```
Raise the number of m_prediction_quanta! currently 20480
Raise the number of m_prediction_molecules! currently 8192
```
Title and description are talking about two different things (quanta vs molecules)

edit: Ah, the molecules mention was just in reference to that's only when this leads to a crash

**Comment by Weaver900** [comment]
> 

Sorry about that, I kinda smushed together two seperate issues. 

The main issue is that the old error message is still displaying even thought the limit has been raised, but this doesn't crash the game.

The secondary "Please please Mr Kornman the ascended lord of all Halo modders" issue is that the m_prediction_molecules limit is still really easy to hit and if it could be raised I'd name my firstborn after you :D

**Comment by kornman00** [comment]
In a future update, H3's m_prediction_quanta and m_prediction_molecules limits will be aligned with at least ODST (there was something else that I aligned with H4, but forget which now).

Please don't name a defenseless child 'korn', man 😛

**Comment by Weaver900** [comment]
> In a future update, H3's m_prediction_quanta and m_prediction_molecules limits will be aligned with at least ODST (there was something else that I aligned with H4, but forget which now).
> 
> Please don't name a defenseless child 'korn', man 😛

Thank you so much, this is great to hear :D I suppose I'll have to name them "00" then, which isn't much better haha

This might be a little off topic, and apologies if I'm asking too much, but is there any future plans to extend these limits for the Reach editing kit also?

**Comment by Weaver900** [comment]
Woops accidently closed, I'm a github noob, sorry about that!

**Comment by kornman00** [comment]
This should be resolved in the 2023/07/12 update.
