### ISSUE TITLE
H2EK: Enable 3rd Person View Flag Option In Guerilla When Not In A Vehicle Or Turret

### ISSUE THREAD

**Issue by xXFerginatorXx** [Joint-Issue-Tracker/Joint-Issue-Tracker#93]
### Issue type: Is this a bug or feature request?

Feature request

### Which game's editing kit is affected by the issue?

H2EK

### Which tools are affected by the issue?

- [X] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [X] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [X] In-game (MCC)

### Issue description

Enable 3rd person view. It would be nice as well for Halo CE. In Halo 2 back in the day there were some community mod tools to do this to get around the limitation but in Halo 2 MCC you either need 3rd party as well or modded DLL files, that once the game is updated by devs, it changes and the DLL no longer works. It would be nice for either an option or make a setting with weapons that have a flag that, like vehicles, enables 3rd person view.

![2023-03-22 22_29_53-Guerilla - G__Program Files (x86)_Steam_steamapps_common_H2EK](https://user-images.githubusercontent.com/128125126/227112334-dd967cd6-ed74-4b95-9293-309efbc3ab55.png)

### Reproduction steps

Just make any mod and try to find any setting but nothing to enable it.

### How often does the issue occur?

100%

### Issue impact

No impact, just would really be nice to have for certain modes where we can forgo the need for fp animations

### Additional comments

One mod I made I want to have players playing as ODSTs but because the first person view is still a spartan it breaks immersion. And Also I feel 3rd person would look way better than first person too

**Comment by Krevil** [comment]
This was added in the 2023/07/12 update.
