### ISSUE TITLE
H2EK: Enable Spartan Usage Of Mongoose

### ISSUE THREAD

**Issue by xXFerginatorXx** [Joint-Issue-Tracker/Joint-Issue-Tracker#96]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

H2EK

### Which tools are affected by the issue?

- [X] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [X] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [X] In-game (MCC)

### Issue description

The default mongoose tag in MCC doesn't work for Spartans. I checked guerilla and couldn't find an option to enable. It worked in old builds but in the final one, available in Sapien, it only works for Spartans. It's not necessarily a big though it was more of an incomplete mechanic that was never finished and forgot to enable for spartans.

### Reproduction steps

Spawn a mongoose in Halo 2, have an elite player get on it and then have a spartan player get on it and you will see the spartan player can't

### How often does the issue occur?

100%

### Additional comments

I don't know how but at least one person showed it working for spartan but not sure if this is a different build they are using and not the actual MCC build

https://www.youtube.com/watch?v=wOTae0TGbdQ

**Comment by xXFerginatorXx** [comment]
Adding here that there is a way to mod, it's a little goofy with the animation but works, to allow spartans to drive H2 mongooses. You just replace mongoose settings in the .vehicle tag and copy some of the ghost .vehicle tags including the mongoose_d to ghost_d 
![2023-03-23 23_15_29-Window](https://user-images.githubusercontent.com/128125126/227749009-f462fcd8-3faf-4584-aef4-bf5a2f510d2e.png)

**Comment by kornman00** [comment]
This should be resolved in the 2023/07/12 update, using the included Digsite content if I recall correctly.
