### ISSUE TITLE
[H4EK] .particle_emitter_custom_points tag causing crashes

### ISSUE THREAD

**Issue by JacobScaife** [Joint-Issue-Tracker/Joint-Issue-Tracker#97]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

H4EK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [X] Foundation (`Foundation.exe`)
- [ ] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

Attempting to open a .particle_emitter_custom_points tag in foundation will cause a crash to desktop.
Tagwatcher.exe will also stop running when it encounters a .particle_emitter_custom_points tag.
This doesn't seem to create any form of crash report.

### Reproduction steps

Opening this tag type in foundation
OR Running tagwatcher.exe

### How often does the issue occur?

100%

### Issue impact

Prevents the building of a full tag database, preventing use of many foundation features.

### Additional comments

Deleting all .particle_emitter_custom_points in the tag hierracy will allow tagwatcher to initialize and run. Re-adding them afterwards will cause tagwatcher to crash the next time it is run

**Comment by General-101** [comment]
This issue was fixed a while ago. Expect a fix in the next tool update
