### ISSUE TITLE
H3EK: Environment Mapping Option Typo

### ISSUE THREAD

**Issue by FaberTheCatgirl** [Joint-Issue-Tracker/Joint-Issue-Tracker#98]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

H3EK

### Which tools are affected by the issue?

- [X] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [ ] Sapien (`sapien.exe`)
- [ ] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

Environment Map Option has a typo `from_flat_exture_as_cubemap` should actually be `from_flat_texture_as_cubemap`
![image](https://user-images.githubusercontent.com/103538724/231270615-da9a3778-23d7-4cf7-8f69-0998da60c8a7.png)

### Reproduction steps

N/A

### How often does the issue occur?

100%

### Issue impact

This bug can prove problematic to third-party mod tools such as `Universal Tag Editor` and `TagTool` as these environmental options must be manually mapped

### Additional comments

Typo may have cascading effects across the shader pipeline

**Comment by FaberTheCatgirl** [comment]
Other Bump Mapping Options appear to possibly contain typos as well. Might also be worth investigating.
![image](https://user-images.githubusercontent.com/103538724/231275495-168306cf-4a9e-468f-a902-695b12f4e0f2.png)

**Comment by kornman00** [comment]
1. Won't fix, the typo is in content, which likely means there's one or more templates with the typo, and then there's one or more shaders using those templates dependent on that typo.
2. unorm is not a typo.
